### PR TITLE
python types columns issues #86

### PR DESCRIPTION
**Pull request by vir-mir**
As I understand it, the problem arose after was merged #55 
effects of problem #86

### CODE REVIEW

**Comment by jettify** [comment]
@popravich could you also take a look?

**Comment by popravich** [comment]
AFAIR, `_result_colums` is remove in sqlalchemy 1.0, so this might not work well with slqalchemy 1+.
Need to take a deeper look

**Comment by vir-mir** [comment]
I think

**Comment by vir-mir** [comment]
I could not find information about the removal _result_colums except that commit https://github.com/zzzeek/sqlalchemy/commit/9854114f578833aee49b65e440319a0ec26daab6

But as I understand it, it affects only DefaultExecutionContext.
I also could not find the use of DefaultExecutionContext in aiopg.
But, for the formation of `result_column_struct` used `compiled.result _result_columns` https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L574

I also use `compiled._result_columns` to form column types https://github.com/vir-mir/aiopg/blob/3b4eaa9eb09377fb8c8ecd28e0fa5e14b1aefa95/aiopg/sa/connection.py#L99

Information about the `compiled._result_columns` removal I have not found.

@popravich what do you think?

**Comment by popravich** [comment]
What version of sqlalchemy do you use?

**Comment by vir-mir** [comment]
SQLAlchemy==1.1.4

In travis too SQLAlchemy https://travis-ci.org/aio-libs/aiopg/jobs/178679293#L467

everything is working :slightly_smiling_face:

**Comment by popravich** [comment]
ok,
`_result_columns` is a private API of Compiled, so using it kinda inconvinient,
but I couldn't find any public API exposing this data.
I think we need a comment near `compiled._result_columns` explaining why this private api is used.

**Comment by vir-mir** [comment]
ok, today add.

I just looked, what the normal use of private API https://github.com/aio-libs/aiopg/blob/master/aiopg/sa/result.py#L119

**Comment by jettify** [comment]
@popravich @asvetlov thoughts? LGTM?

**Comment by asvetlov** [comment]
LGTM

**Pull request merged**
