### PR TITLE
Remove blocking connection.cancel() method

### LINKED ISSUE #375: Aiopg blocks event loop during query cancel
If cursor is configured with timeout, then upon expiration of this timeout psycopg2 tries to call libpq's PQcancel() which tries to connect to postgres via different connection and close previous backend. In case when server is really unaccessible this will block event loop. Also this connection attempt doesn't inherit timeout of aiopg.connect().

Here is script to reproduce problem: https://gist.github.com/kelvich/7ca3dcaa279f76e004b88e40c7354025

It starts two loops in separate coroutines, one of which is doing database queries, other one just prints "tick" every second to illustrate blocking. To block evloop one need to block network connections to database, for example in docker container:

```sh
# in first console
docker run -p 5432:5432 --name pg postgres:alpine
# in second console
python3 ./aiopg_stuck.py
```

then we can go inside our container with postgres `docker exec -ti -u root --privileged pg sh` and block network:

```sh
apk --update add iptables
iptables -A INPUT -j DROP && iptables -A OUTPUT -j DROP
```

evloop will hang after that.

### LINKED ISSUE #491: connection.cancel can hang
we noticed this callstack in our prod server which hung our main thread breaking the server:

```
Jul 30 16:48:45.114            File "/usr/local/lib/python3.6/asyncio/base_events.py", line 422 in run_forever
Jul 30 16:48:45.114            File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1434 in _run_once
Jul 30 16:48:45.114            File "/usr/local/lib/python3.6/asyncio/events.py", line 145 in _run
Jul 30 16:48:45.114            File "/usr/local/lib/python3.6/site-packages/aiopg/connection.py", line 226 in cancel
```

suggest `loop.run_in_executor`'ing it as supposedly this method is thread safe.  Ideally there would be a timeout that affects this as well.  I'm not sure if the DSN `connect_timeout` applies

### PR DESCRIPTION
**Pull request by brianmaissy**
Closes #491 
Closes #375

### CODE REVIEW

**Comment by brianmaissy** [comment]
Is this going to actually be merged if I go through the CLA process?

**Comment by Pliner** [comment]
@brianmaissy Thanks for rebasing, I've missed it.

**Review by Pliner — APPROVED** [review]

**Comment by Pliner** [comment]
@asvetlov Are you ok with this PR?

I'm going to merge and release it as 1.2beta if so.

**Comment by Pliner** [comment]
Well, let's merge it and test. @asvetlov any later suggestions are welcome

@brianmaissy Will you be able to test it on your workload?

**Comment by brianmaissy** [comment]
Yes

**Comment by Pliner** [comment]
> Yes. Are you going to release a beta build?

Thanks. https://pypi.org/project/aiopg/1.2.0b1/

**Comment by brianmaissy** [comment]
seems to be working fine 👍

**Comment by Pliner** [comment]
> seems to be working fine 👍

Thanks 🔥 

I'm going to test it during the next week as well.

**Comment by brianmaissy** [comment]
@Pliner I think I found what may be a problem: if a `TimeoutError` is raised while waiting for a query while in a transaction context manager, it used to cancel the query, and then run the `ROLLBACK`. Now it closes the connection, and when it tries to run the `ROLLBACK` it throws a `psycopg2.InterfaceError: connection already closed` exception. I have a test which replicates the problem, should I open a new ticket and PR?

**Comment by Pliner** [comment]
> @Pliner I think I found what may be a problem: if a `TimeoutError` is raised while waiting for a query while in a transaction context manager, it used to cancel the query, and then run the `ROLLBACK`. Now it closes the connection, and when it tries to run the `ROLLBACK` it throws a `psycopg2.InterfaceError: connection already closed` exception.

@brianmaissy I have the same trouble 👍 

> I have a test which replicates the problem, should I open a new ticket and PR?

Yes, please 😊

**Pull request merged**
