### PR TITLE
Add explicit sequence and returning declarations

### PR DESCRIPTION
**Pull request by eirnym**
We should use explicit sequence for ID columns.
We should use explicit returning.

Without these changes this example won't work on SQLAlchemy 0.9.9+ even if you remove all async-specific code.

### CODE REVIEW

**Comment by asvetlov** [comment]
First, you change doesn't pass PEP8 checker.
Second, I've checked current aiopg tests/examples on sqlalchemy 0.9.9 and see no issue.
Would you describe how to reproduce the error you trying to fix?
I agree in general that explicit specifications produced by you is good idea but as I see the old way is also works.

**Comment by eirnym** [comment]
When I've tried to run this example I've got 2 exceptions:

```python
    Traceback (most recent call last):
      File "sa.py", line 68, in fill_data
        name=name, birthday=gen_birthday()))
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/sa/connection.py", line 115, in scalar
        res = yield from self.execute(query, *multiparams, **params)
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/sa/connection.py", line 102, in execute
        yield from cursor.execute(str(compiled), post_processed_params[0])
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/cursor.py", line 111, in execute
        yield from self._conn._poll(waiter, timeout)
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/connection.py", line 155, in _poll
        yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
        return fut.result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/connection.py", line 90, in _ready
        state = self._conn.poll()
    psycopg2.IntegrityError: null value in column "id" violates not-null constraint
    DETAIL:  Failing row contains (null, Dave, 1985-03-11 00:00:00).
```

And this (when I've modified this example to the sync version (with same main code):
```python
Traceback (most recent call last):
      File "test.py", line 128, in <module>
        go()
      File "test.py", line 123, in go
        fill_data(engine)
      File "test.py", line 62, in fill_data
        name=name, birthday=gen_birthday())
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 771, in scalar
        return self.execute(object, *multiparams, **params).scalar()
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/sqlalchemy/engine/result.py", line 857, in scalar
        row = self.first()
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/sqlalchemy/engine/result.py", line 834, in first
        self._non_result()
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/sqlalchemy/engine/result.py", line 755, in _non_result
        "This result object does not return rows. "
    sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```

**Comment by asvetlov** [comment]
Hmm, I really have no idea what's going wrong. My console output:
'''
andrew•~/projects/aiopg(master)» python examples/simple_sa.py                                                                  (aiopg)  [14:47:49]
1 abc
andrew•~/projects/aiopg(master)» python examples/sa.py                                                                         (aiopg)  [14:48:18]
Population consists of 25 people with 35 emails in total
Users with public emails:
Julia
Margo
Dave
Ivy
Lina
Rita
Rosa
Eva
Matt

Lookup for Julia:
Julia 1992-06-18 00:00:00 Julia+649@gmail.com False
Julia 1992-06-18 00:00:00 Julia+7693@gmail.com True
Julia 1992-06-18 00:00:00 Julia+7858@gmail.com True

Average age of population is 8992 days, 12:28:48 or ~ 24 years

andrew•~/projects/aiopg(master)» pip list                                                                                      (aiopg)  [14:48:23]
aiopg (0.6.1, /home/andrew/projects/aiopg)
coverage (3.7.1)
docutils (0.11)
elpy (1.5.1)
flake8 (2.2.3)
ipdb (0.8)
ipython (2.1.0)
jedi (0.8.1-final0)
Jinja2 (2.7.3)
MarkupSafe (0.23)
mccabe (0.2.1)
pep8 (1.5.7)
pip (1.5.6)
psycopg2 (2.6)
pyflakes (0.8.1)
Pygments (1.6)
readthedocs-sphinx-ext (0.4.3)
setuptools (5.3)
Sphinx (1.2.2)
SQLAlchemy (0.9.9)
wheel (0.23.0)
'''
Did you run tests on your box? `make test` command is for test suite execution.

**Comment by eirnym** [comment]
what to do with this exception on `yield from conn.execute(table.insert().values(key1=val1))` ?

    Traceback (most recent call last):
      File "test.py", line 102, in <module>
        loop.run_until_complete(go())
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
        return future.result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 238, in _step
        result = next(coro)
      File "test.py", line 98, in go
        yield from fill_data(engine)
      File "test.py", line 79, in fill_data
        language='plain/text')
      File "/Users/eirnym/Development/sdk/python/34/ens/lib/python3.4/site-packages/aiopg/sa/connection.py", line 95, in execute
        result_map = compiled.result_map
    AttributeError: 'PGCompiler_psycopg2' object has no attribute 'result_map'

**Comment by asvetlov** [comment]
Please upgrade to aiopg 0.7.0

**Comment by eirnym** [comment]
PostgreSQL (MacPorts): Version string	PostgreSQL 9.4.1 on x86_64-apple-darwin14.0.0, compiled by Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn), 64-bit

    $ make test
    pep8 aiopg examples tests
    pyflakes .
    python3 runtests.py 
    ..E.....................s....................x...................................................................................................................................................
    ======================================================================
    ERROR: test_binary_protocol_error (tests.test_connection.TestConnection)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/test_connection.py", line 553, in test_binary_protocol_error
        self.loop.run_until_complete(go())
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
        return future.result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 238, in _step
        result = next(coro)
      File "tests/test_connection.py", line 551, in go
        yield from cur.execute('SELECT 1')
      File "/Users/eirnym/Development/external/0.python/0.asyncio/aiopg/aiopg/cursor.py", line 112, in execute
        yield from self._conn._poll(waiter, timeout)
      File "/Users/eirnym/Development/external/0.python/0.asyncio/aiopg/aiopg/connection.py", line 162, in _poll
        yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 377, in wait_for
        return fut.result()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
        raise self._exception
      File "/Users/eirnym/Development/external/0.python/0.asyncio/aiopg/aiopg/connection.py", line 97, in _ready
        state = self._conn.poll()
    psycopg2.DatabaseError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


    ----------------------------------------------------------------------
    Ran 193 tests in 8.669s

    FAILED (errors=1, skipped=1, expected failures=1)
    make: *** [test] Error 1

**Comment by eirnym** [comment]
Does aiopg.sa handle default values?

**Comment by eirnym** [comment]
Thank you about upgrade notification!

**Comment by eirnym** [comment]
pip freeze:

aiopg==0.7.0
alabaster==0.7.3
Babel==1.3
certifi==14.5.14
Chameleon==2.22
coverage==3.7.1
dictalchemy==0.1.2.6
docutils==0.12
empy==3.3.2
flake8==2.4.0
Flask==0.10.1
Genshi==0.7
gnureadline==6.3.3
ipython==3.1.0
itsdangerous==0.24
Jinja2==2.7.3
Kajiki==0.4.4
Mako==1.0.1
MarkupSafe==0.23
mccabe==0.3
nine==0.3.4
nose==1.3.6
peewee==2.5.1
pep8==1.6.2
psycopg2==2.6
pyflakes==0.8.1
Pygments==2.0.2
pyratemp==0.3.2
pytz==2015.2
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.7
SQLAlchemy==1.0.0
SQLAlchemy-Utils==0.29.9
tornado==4.1
transmissionrpc==0.11
Werkzeug==0.10.4

**Comment by asvetlov** [comment]
@eirnym 
1. Failed test_binary_protocol_error in your report looks strange to me. Cannot reproduce. Would you run tests several times? Is it constant problem or is it vanishing? Is it Mac only?
2. aiopg doesn't support default values, only server_default ones.

**Pull request closed without merging**
