### PR TITLE
Added test for default values on insert (Test first)

### PR DESCRIPTION
**Pull request by eirnym**
Defaults are not supported for now

### CODE REVIEW

**Comment by eirnym** [comment]
Sample working code to help to fix this test:

    @asyncio.coroutine
    def get_column_default(engine, column):
        default = column.default
        dialect = engine.dialect
        if default.is_sequence:
            sql = "select nextval('%s')" % \
                dialect.identifier_preparer.format_sequence(default)
            print(sql)
            with (yield from engine) as conn:
               return (yield from conn.scalar(sql))
        elif default.is_clause_element:
            with (yield from engine) as conn:
               return (yield from conn.scalar(default.arg))
        elif default.is_callable:
            return default.arg(dialect)
        else:
            return default.arg

    @asyncio.coroutine
    def get_table_defaults(engine, table):
        result = {}
        for column in table.c:
            if column.default is not None:
                result[column.name] = (yield from get_column_default(engine, column))
        return result

    @asyncio.coroutine
    def insert(engine, table, returning_id=False, **kwargs):
        values = yield from get_table_defaults(engine, table)
        values.update(kwargs)
        print(values)
        if returning_id:
            insertion = table.insert(returning=[table.id])
        else:
            insertion = table.insert()
        return insertion.values(**values)

**Comment by eirnym** [comment]
But better way is to implement somehow ExecutionContext if it possible with mixing async and not async code.

**Comment by eirnym** [comment]
Added test for this override

**Comment by asvetlov** [comment]
@eirnym I don't know how to hack ExecutionContext but maybe calculating defaults in `SAConnection.execute()` may help?
See https://github.com/aio-libs/aiopg/blob/master/aiopg/sa/connection.py#L71 for the modification point  what I guess.

**Comment by eirnym** [comment]
Test `test_defaults_override `, uses function which extracts defaults from table and uses almost same code as in SQLAlchemy . I'll try do same with onupdate later.

**Comment by eirnym** [comment]
@asvetlov It's not too easy to put this into connection. `Connection` object executes `dialect` first, then dialect executes `connection._cursor_execute`, which executes `dialect.dispatch` methods for events, defaults and so on.

So version with fabric is more stable and understandable for others than that *hack* which is used in `SQLAlchemy`.

**Comment by eirnym** [comment]
In other words, it's easer to rewrite entire `SQLAlchemy` to use `asyncio` than inject defaults into `Connection` object.

**Comment by asvetlov** [comment]
If there is impossible to use native SQLAlchemy defaults processing in our code we should document it explicitly to encourage people using our versions of `insert` and `update` functions.

Maybe we still can support default like constant and callable for native queries and force user to use our functions for sequences and clauses?

**Comment by vir-mir** [comment]
I close, problem with default value for column resolved here -> (https://github.com/aio-libs/aiopg/pull/206)

**Pull request closed without merging**
