### PR TITLE
Fix closing of transaction

### LINKED ISSUE #332: Error when canceling during transaction begin.
I'm seeing an issue when my coroutine is cancelled while trying to begin a transaction:
```python
async with self.db.replica.acquire() as conn, conn.begin():
    res = await conn.execute(query)
    return await res.scalar()
```
```python
Traceback (most recent call last):
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 235, in get_current_version
    async with self.db.replica.acquire() as conn, conn.begin():
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/utils.py", line 77, in __aenter__
    self._obj = yield from self._coro
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/connection.py", line 171, in _begin
    yield from self._begin_impl()
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/connection.py", line 180, in _begin_impl
    yield from cur.execute('BEGIN')
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/cursor.py", line 113, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/connection.py", line 240, in _poll
    raise exc
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/connection.py", line 237, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/opt/python3.6/lib/python3.6/asyncio/tasks.py", line 345, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 354, in middleware
    return await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 385, in middleware
    response = await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/authentication/__init__.py", line 42, in middleware
    return await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/health.py", line 37, in health_check
    'data_version': await request.app.get_current_version(),
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 237, in get_current_version
    return await res.scalar()
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/utils.py", line 140, in __aexit__
    yield from self._pool.release(self._conn)
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/engine.py", line 169, in release
    raise InvalidRequestError("Cannot release a connection with "
aiopg.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction 
```

It seems like the issue occurs when the [cursor coroutine](https://github.com/aio-libs/aiopg/blob/ba3a3424680215be28033b03c180a0683028dbf9/aiopg/sa/connection.py#L178) is interrupted. This is after [the `_transaction` is set on the SA connection](https://github.com/aio-libs/aiopg/blob/ba3a3424680215be28033b03c180a0683028dbf9/aiopg/sa/connection.py#L170), but since the error is in the `_TransactionContextManager`'s `__aenter__`, its `__aexit__` is never called to issue a rollback (oddly the `__aexit__` seems to be called successfully if the error is in the `try: finally:` block below this. I don't understand how this happens). Since we have a transaction, and it's not "finished" (although technically it was never started), the engine doesn't realize it can release the connection.

### PR DESCRIPTION
**Pull request by decaz**
In case of errors within a transaction (for example, connection errors) connection can't be released due to a transaction is still considered active. So we should guarantee deactivating of transaction in case of commit or rollback.

Fixes #332.

### CODE REVIEW

**Comment by asvetlov** [comment]
There is no guarantee to have a connection in a good state after cursor closing.
Even cursor closing may fail if internal invariants are broken.
I think the better solution is closing the connection entirely.

**Comment by decaz** [comment]
@asvetlov reproduction of the problem is pretty simple:
```python
import asyncio

import aiopg.sa
import psycopg2

DSN = 'host=localhost dbname=test user=test password=test'


async def run():
    engine = await aiopg.sa.create_engine(DSN)
    async with engine.acquire() as conn, conn.begin():
        await conn.execute('SELECT pg_sleep(30)')


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```
Run the script and immediately shutdown/restart PotsgreSQL server. The result is:
```
Traceback (most recent call last):
  File "../test_aiopg_tx.py", line 12, in run
    await conn.execute('SELECT pg_sleep(30)')
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/utils.py", line 71, in __await__
    resp = yield from self._coro
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/sa/connection.py", line 74, in _execute
    yield from cursor.execute(query, dp)
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/cursor.py", line 114, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/connection.py", line 238, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/connection.py", line 135, in _ready
    state = self._conn.poll()
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../test_aiopg_tx.py", line 12, in run
    await conn.execute('SELECT pg_sleep(30)')
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/utils.py", line 138, in __aexit__
    yield from self._obj.rollback()
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/sa/transaction.py", line 68, in rollback
    yield from self._do_rollback()
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/sa/transaction.py", line 109, in _do_rollback
    yield from self._connection._rollback_impl()
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/sa/connection.py", line 195, in _rollback_impl
    cur = yield from self._connection.cursor()
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/utils.py", line 66, in __iter__
    resp = yield from self._coro
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/connection.py", line 283, in _cursor
    withhold=withhold)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/connection.py", line 291, in _cursor_impl
    scrollable=scrollable, withhold=withhold)
psycopg2.InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../test_aiopg_tx.py", line 16, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "../test_aiopg_tx.py", line 12, in run
    await conn.execute('SELECT pg_sleep(30)')
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/utils.py", line 155, in __aexit__
    yield from self._pool.release(self._obj)
  File "/home/decaz/.virtualenvs/exp/lib/python3.6/site-packages/aiopg/sa/engine.py", line 178, in release
    raise InvalidRequestError("Cannot release a connection with "
aiopg.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction
```
The `psycopg2.OperationalError` is OK, but attempt to close the transaction is very strange as the connection failed. How should we go in this case? Should I create the connection and transaction objects manually instead of use of context managers and try to catch any errors for correct release of transaction?

**Comment by asgoel** [comment]
@decaz did you ever come up with a good fix for this?

**Comment by decaz** [comment]
What do you mean by "good"?

**Comment by asgoel** [comment]
A solution to the original issue you were trying to fix. It doesn't look like this particular PR got merged in, so was wondering if you had come up with a workaround.

**Comment by decaz** [comment]
Unfortunately, I don't have any other solution to fix this issue, but I think that this PR is not bad and still waiting for any answer on [my question](https://github.com/aio-libs/aiopg/pull/487#issuecomment-412819528) (FYI @asvetlov).

**Comment by asgoel** [comment]
@asvetlov did you have an opinion on this issue?

**Pull request closed without merging**
