### PR TITLE
Rename `psycopg2` to `psycopg2-binary` to fix deprecation warning

### LINKED ISSUE #445: psycopg2 renaming
I think this library triggers the following warning:

```
env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```

i noticed this while running `adev runserver` from aiohttp-devtools

### PR DESCRIPTION
**Pull request by orf**
Fixes #445

### CODE REVIEW

**Comment by thehesiod** [comment]
I'm not sure this is correct, the recommended binary to use is still psycopg2 as it will link the the library on your system, no?

**Comment by orf** [comment]
Nope. The `postgresql_psycopg2binary` option only exists in the latest sqlachemy. With this we always install the prebuilt wheel, so we are all good. Sqlalchemy does not force us to install the plain `psycopg2` package at all.

**Comment by Faunris** [comment]
Hello. It looks good.
Plase, resolve conflict in setup.py.

**Comment by orf** [comment]
Done 👍

**Comment by Faunris** [comment]
Ohmg, you broke tests 8)

**Comment by orf** [comment]
Interesting, [this line](https://codecov.io/gh/aio-libs/aiopg/compare/514f8785b5897cbf2a6719a2bde203968a986827...97ca4d0e6af097fb6deed7009d1922d69fe30948/src/tests/test_connection.py) is not tested anymore? IDK why.

**Comment by Faunris** [comment]
Thank you)

@asvetlov 
I think this can be merged

discuss about rename psycopg2 to psycopg2-binary:
https://www.postgresql.org/message-id/CA%2Bmi_8bd6kJHLTGkuyHSnqcgDrJ1uHgQWvXCKQFD3tPQBUa2Bw%40mail.gmail.com

explanation: http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

**Comment by Faunris** [comment]
Wow! We need update sqlalchemy to 1.2 for sqlalchemy[postgresql_psycopg2binary]

**Comment by orf** [comment]
No, we do not. There will be a warning from pip that the extra is not found
in sqlalchemy 1.1, but this is fine.

**Comment by orf** [comment]
Any chance of merging this @vir-mir ?

**Comment by yabirgb** [comment]
Can we merge this?

**Pull request merged**
