### PR TITLE
Allow for custom aiopg connection factories

### PR DESCRIPTION
**Pull request by luhn**
This is so I can do this:  https://gist.github.com/luhn/e4972184e1e1e724a430

### CODE REVIEW

**Comment by luhn** [comment]
Tests failing for same reason as #72

**Comment by asvetlov** [comment]
What's your use case for the PR?
`aiopg.Connection` is not intended for inheritance.

**Comment by luhn** [comment]
See the gist I linked above.
On Wed, Sep 23, 2015 at 7:42 AM Andrew Svetlov <notifications@github.com>
wrote:

> What's your use case for the PR?
> aiopg.Connection is not intended for inheritance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiopg/pull/74#issuecomment-142622955>.
>
-- 
Regards,
Theron Luhn
CTO, Guest Innovations

**Comment by asvetlov** [comment]
For your case you shouldn't derive from Connection but embed connection instance inside your class with `.query` and `operation` methods -- like I did it for SQLAlchemy support (https://github.com/aio-libs/aiopg/blob/master/aiopg/sa/connection.py)

**Comment by luhn** [comment]
I feel it's excessive to add another layer of abstraction just for a couple of convenience functions.  But perhaps you're right.  I can't find an example of anybody else subclassing a database connection.

**Comment by asvetlov** [comment]
Let's close the issue.

**Pull request closed without merging**
