### PR TITLE
Timeout on aquiring connection from pool

### PR DESCRIPTION
**Pull request by beezz**
This PR implements timeout on acquiring connection from pool using the [async-timeout](https://github.com/aio-libs/async-timeout) lib. (#130)

### CODE REVIEW

**Comment by beezz** [comment]
I'd love to provide some tests for this as well, but can't think of reasonable way. Any suggestions? Maybe connection to non-existent server with zero timeout would do the trick.

**Comment by jettify** [comment]
Thank you for your contribution, but this change will break library for tornado users, for more information see: https://github.com/KeepSafe/aiohttp/issues/1180

**Comment by stopspazzing** [comment]
Latest info related to timeout and aiohttp here: https://github.com/aio-libs/aiohttp/issues/1524

Should this PR be updated to merge or closed?

**Comment by asvetlov** [comment]
The PR should wait for Tornado 5 I think.

**Pull request closed without merging**
