### PR TITLE
Set an Event when the connection is closed

### PR DESCRIPTION
**Pull request by gclinch**
This allows other waiters (eg waiting on Connection.notifies.get()) to be woken when the connection will never generate more notifications.

Would solve Issue #249 with the use of
`asyncio.wait([connection.closure_event.wait(), connection.notifies.get()], return_when=FIRST_COMPLETED)`

### CODE REVIEW

**Comment by gjcarneiro** [comment]
This patch didn't solve the problem for me.
I suspect we need something like aioredis' [ClosableQueue](https://github.com/aio-libs/aioredis/blob/master/aioredis/pubsub.py#L397)

**Comment by gjcarneiro** [comment]
Oh, I see, I didn't read carefully enough.  This patch requires API changes.

I think it's not good enough: IMHO, aiopg should raise an exception when waiting for pg notify and the underlying connection got closed.

Requiring the developer to explicitly use the `Event()` object means that most developers will not even be aware of the bug until it bites them in production.

In contrast, an exception raised will most likely be caught somewhere.

**Comment by gjcarneiro** [comment]
I made another PR (#559) that, imho, is a better approach.  It also uses an event, but it is used transparently but the `connection.notifies.get()` coroutine.  Makes life a lot simpler for developers.

**Comment by vir-mir** [comment]
thank. I need a little more time, I plan to start merge into master by the end of next week

**Comment by gjcarneiro** [comment]
No pressure from me, not in a big hurry, I have a workaround for the problem. ;)

**Comment by Pliner** [comment]
Fixed by #559

**Pull request closed without merging**
