### PR TITLE
SQLAlchemy 2.0 compatibility

### PR DESCRIPTION
**Pull request by mayty**
## What do these changes do?

Fix SQLAlchemy 2.0 compatibility

## Are there changes in behavior for the user?

No

## Related issue number

[897.bugfix](https://github.com/aio-libs/aiopg/issues/897)

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Pliner** [comment]
Hey @mayty,

Thank you for the contribution.

I have pushed CI changes (not ideal through) to run tests on both major versions of sqlalchemy.

**Comment by Pliner** [comment]
The changes look reasonable for me, so I am happy to merge and release a new beta version. 

@mayty Do you want to include any other additional changes into this PR?

**Comment by mayty** [comment]
Hi
That's all the changes I want to include

But older version sqlalchemy test should probably be limited to `>=1.4,<1.5`. They would fail on `1.3` due to new syntax

**Comment by Pliner** [comment]
> Hi That's all the changes I want to include
> 
> But older version sqlalchemy test should probably be limited to `>=1.4,<1.5`. They would fail on `1.3` due to new syntax

Thanks for pointing this out. I have bumped a min supported sqlalchemy version to 1.4.

**Comment by Pliner** [comment]
@mayty I was thinking to release it as 1.5 with a minor version bump. What do you think?

**Comment by mayty** [comment]
I agree

**Comment by Pliner** [comment]
https://pypi.org/project/aiopg/1.5.0a1/

**Pull request merged**
