### PR TITLE
Fix compatibility with SQLAlchemy >= 1.4

### LINKED ISSUE #869: Incompatibility with SQLAlchemy 1.4
### Describe the bug

`AttributeError: module 'sqlalchemy.sql.expression' has no attribute '_string_or_unprintable'` is raising here:
https://github.com/aio-libs/aiopg/blob/10071ff27b4bc4560c61cd183534587cb24f586b/aiopg/sa/result.py#L201

### To Reproduce

Call undefined column on row.

### Expected behavior

Exception `NoSuchColumnError` is raised.

### Logs/tracebacks

```python-traceback
...
  File "/home/decaz/workspace/project/.venv/lib/python3.9/site-packages/aiopg/sa/result.py", line 55, in __getattr__                                                                                   
    return self[name]                                                                                                                                                                                             
  File "/home/decaz/workspace/project/.venv/lib/python3.9/site-packages/aiopg/sa/result.py", line 29, in __getitem__                                                                                   
    processor, obj, index = self._result_proxy._key_fallback(key)                                                                                                                                                 
  File "/home/decaz/workspace/project/.venv/lib/python3.9/site-packages/aiopg/sa/result.py", line 201, in _key_fallback                                                                                
    f"{expression._string_or_unprintable(key)!r}"                                                                                                                                                                 
AttributeError: module 'sqlalchemy.sql.expression' has no attribute '_string_or_unprintable'
```

### Python Version

```console
3.9.6
```

### aiopg Version

```console
1.3.1
```

### OS

Linux

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

### PR DESCRIPTION
**Pull request by decaz**
## What do these changes do?

Fix compatibility with SQLAlchemy >= 1.4.

## Related issue number

Fixes #869.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by Pliner** [comment]
Thanks for your contribution. I will be able to review PR tomorrow.

**Review by Pliner — APPROVED** [review]
Looks good, thanks. Have you run the tests against SQLAlchemy v1.3?

**Comment by decaz** [comment]
@Pliner yes, I also added test for this exception. I think it will be nice to include SQLAlchemy version in CI job matrix in the future for testing against ==1.3 and >=1.4 versions.

**Comment by Pliner** [comment]
> @Pliner yes, I also added test for this exception. I think it will be nice to include SQLAlchemy version in CI job matrix in the future for testing against ==1.3 and >=1.4 versions.

Cool. 

If you have time and you know how to do this, feel free to create a PR.

**Review by Pliner — APPROVED** [review]

**Comment by Pliner** [comment]
https://pypi.org/project/aiopg/1.3.2b1/

**Comment by Pliner** [comment]
@decaz Have you had a chance to test this version in a production environment?

**Comment by decaz** [comment]
@Pliner not yet, - I'm trying to migrate my code base from SQLAlchemy 1.3 to 1.4 and while I run tests now there is no errors related to `string_or_unprintable`. But there are errors related to #798 :(

**Pull request merged**
